apiVersion: v1
kind: Secret
metadata:
  name: products-db-credentials
  namespace: products-namespace
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXMxMjM=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: products-namespace
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://products-db:5432/products
    spring.datasource.username=postgres
    spring.datasource.password=postgres123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app
  namespace: products-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: nikolovaradica/products-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://products-db-service:5432/products
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-db-credentials
                  key: username
            - name: SPRING_DATASOUCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-db-credentials
                  key: password